namespace VpnRouter.WfpSpike.Contracts;

public enum WfpAppIdentityKind { DesktopAppId, PackageId }
public enum WfpIpVersion { IPv4, IPv6 }
public enum WfpSpikeOutcome { PASS, FAIL, NOT_RUN }
public enum WfpSpikeVerdict { PASS, FAIL, PARTIAL }

public enum WfpSpikeResultCode
{
    NONE,
    ADMIN_REQUIRED,
    EXPLICIT_OPTION_REQUIRED,
    AUTOMATED_GATE_FAILED,
    APP_PATH_INVALID,
    APP_ID_LOOKUP_FAILED,
    PACKAGE_IDENTITY_UNAVAILABLE,
    PACKAGE_ID_LOOKUP_FAILED,
    INTERFACE_NOT_FOUND,
    INTERFACE_IDENTITY_MISMATCH,
    BFE_ACCESS_DENIED,
    ENGINE_OPEN_FAILED,
    POLICY_ALREADY_EXISTS,
    IPV4_POLICY_ADD_FAILED,
    IPV6_POLICY_ADD_FAILED,
    SESSION_CLOSE_FAILED,
    INTERFACE_CHANGED,
    NEW_CONNECTION_NOT_OBSERVED,
    UNEXPECTED_INTERFACE,
    DNS_APP_ID_NOT_PROPAGATED,
    OWNER_ABORTED,
    PROHIBITED_PATTERN_FOUND,
    PUBLISH_CONTENT_MISSING,
    ENVIRONMENT_UNAVAILABLE
}
